### ISSUE TITLE
Create a Readme File.

### ISSUE THREAD

**Issue by Bhavya0304** [Bhavya0304/MyResume-Web-App-backend#4]
## Create a README.md File.

**You can use any fancy templete to create a README File that contains following Meta-Info**
## Must be Included
1. About Project
2. Setup and Run Locally
3. FAQs

**Comment by Yash-suthar** [comment]
please assign me that issue

**Comment by Bhavya0304** [comment]
Sure! best of luck...

**Comment by Bhavya0304** [comment]
Work done!
